### ISSUE TITLE
VirusTotal detection

### ISSUE THREAD

**Issue by infinitytec** [belowaverage-org/SuperGrate#68]
I noticed that the latest version (v 1.3.5.0) and the previous one (v 1.3.4.0) (I didn't test any others) are triggering a few positives in VirusTotal. I noticed it with the .zip and the 32-bit executable but the 64-bit executable tested fine. Only 1 or 2 total detections so likely a false positive.

**Comment by krisdb2009** [comment]
The more the 32 bit file is used out in the wild the more it will grow a reputation with these security vendors.

I used to submit the executables to these vendors but gave up since it is a pain.

I think the way to work around this issue would be to get the executables signed but it would cost about 500 dollars to get a certificate and it would only last for a year. So way out of my price range unfortunately.
